ics_2022_s1_p1 = {'document_id': '19sDv_eBO4xjey9e2oD-sjRoHk987VKud5-VWNMA0vKE',
                  'classroom_id': 'Mzg5MTY2MTY2NTU2',
                  'spreadsheet_id': '1hv_lxUygEZ2Q_oy8JbdF_bx8VuaDXkkonrOlHa-tVwU',
                  'sheet_id': 'ICS_S1P1',
                  'header_text': 'Intro to Computer Science\n',
                  'course_id': 389166166556,
                  'course_contract': 'https://docs.google.com/document/d/10UgK6pP2UcaXu8ErPBk_MNNDZ82i93AwijWXLplN01M/edit?usp=drive_open&ouid=110067882309555165220',
                  'zoom_links': ['https://zoom.us/j/5163593350?pwd=MzVVRktGcVZ4a0tEbXRwRGJDaFAxZz09'],
                  'assignments_dictionary': {},
                  'fy': False,
                  'calendar_name': 'Murphy S1 P1 Intro to CS',
                  }
it2_2022_fy_p3 = {'document_id': '1cljYfbuUmA9iSP3owt3Br2fBn8GSZm35P-1A9Rfl8ZM',
                  'classroom_id': 'Mzg5MTY5MjY5NjU5',
                  'spreadsheet_id': '1A02osrwMJ2zdf9W8bE8bdd67IfMjDoO0h0N1Pk2GKeg',
                  'sheet_id': 'IT2',
                  'header_text': 'Cybersecurity/Info Tech 2\n',
                  'course_id': 389169269659,
                  'course_contract': 'https://docs.google.com/document/d/1_6njCTlL9QU9y7RGognxUF98jsHsGT9RjTgA7W6WFPU/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': True
                  }
it3_2022_fy_p3 = {'document_id': '1YYfSOPQLnX-szWafXFFuXu6SRkk3JYAuNhJl4G-lqbc',
                  'classroom_id': 'Mzg5MTgxMzM5Mjg1',
                  'spreadsheet_id': '1A02osrwMJ2zdf9W8bE8bdd67IfMjDoO0h0N1Pk2GKeg',
                  'sheet_id': 'IT3',
                  'header_text': 'Cybersecurity/Info Tech 3\n',
                  'course_id': 389181339285,
                  'course_contract': 'https://docs.google.com/document/d/1_6njCTlL9QU9y7RGognxUF98jsHsGT9RjTgA7W6WFPU/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': True
                  }
it1_2022_fy_p1 = {'document_id': '14uKkNw6tHo8foESJsgNcLpKNtjYcEkOhQ8ZDfdC4iRI',
                  'classroom_id': 'Mzg4ODk5OTY3NjU1',
                  'spreadsheet_id': '1veaJaPo--jFET5b5LGi71RujwKtIq4IAmuWu3YX8tUo',
                  'sheet_id': 'IT1/CS1',
                  'header_text': 'Level 1 Intro to CS/Cybersecurity\n',
                  'course_id': 388899967655,
                  'course_contract': 'https://docs.google.com/document/d/'
                                     '1zJArrh4Xq0YlF-vFZu3SCYznJhjMpM9pBs2GOLSsJV0/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': True
                  }

web_2022_s1_p2 = {'document_id': '16NOrXYyOCI_VZYEhi7VgyzJlysp6CnOVIbokAk-ZkrA',
                  'classroom_id': 'Mzg4ODk0NTQxMjc4',
                  'spreadsheet_id': '1ysWjn5UiMbLcB5EyYT7DtEFdr7HruLmKkIasnGv-UHs',
                  'sheet_id': 'T527A',
                  'header_text': 'Web Development\n',
                  'course_id': 388894541278,
                  'course_contract': 'https://docs.google.com/document/d/1fcWp1rsAPTt0s48HRxABHsvQWKuwOBFuEInSritw02E/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': False
                  }
apcsp_2022_s1_p1 = {'document_id': '1LbKCRPsGATdy0HREKPVnk05L0TNTAlHYm2qipvtFYTg',
                    'classroom_id': 'Mzg4OTAwMTg5NjU2',
                    'spreadsheet_id': '1veaJaPo--jFET5b5LGi71RujwKtIq4IAmuWu3YX8tUo',
                    'sheet_id': 'APCSP_S1_P1',
                    'header_text': 'AP CSP S1 P1\n',
                    'course_id': 388900189656,
                    'course_contract': 'https://docs.google.com/document/d/1eR5rxgTZ0PXy_fYIFK2SS_Ro770IXxT9sM90vZr_OcU/edit',
                    'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09',
                                   'https://us02web.zoom.us/j/7890036306?pwd=WlpkV1JKUXZlQ3orYTd2dFBhZkdzdz09'],
                    'assignments_dictionary': {
                        'Create task practice 1': 'Create task practice',
                        'Create task practice 2': 'Create task practice',
                        'Create task practice 3': 'Create task practice',
                        'Create task practice 4': 'Create task practice',
                        'Create task practice 5': 'Create task practice',
                        'Create task practice 6': 'Create task practice',
                        'Create task 1': 'Create task',
                        'Create task 2': 'Create task',
                        'Create task 3': 'Create task',
                        'Create task 4': 'Create task',
                        'Create task 5': 'Create task',
                        'Create task 6': 'Create task',
                        'Create task 7': 'Create task',
                        'Create task 8': 'Create task',
                        'Create task 9': 'Create task',
                        'Create task 10': 'Create task',
                        'Create task 11': 'Create task',
                        'Create task 12': 'Create task',
                    },
                    'fy': False,
                    }

apcsp_2022_s1_p4 = {'document_id': '1fWlXp_aKR9Ak3dRnBk3dtMlR3Ro7nSyUp3-Mrz4y11Q',
                    'classroom_id': 'Mzg4ODk5OTUzNTcw',
                    'spreadsheet_id': '1veaJaPo--jFET5b5LGi71RujwKtIq4IAmuWu3YX8tUo',
                    'sheet_id': 'APCSP_S1_P4',
                    'header_text': 'AP CSP S1 P4\n',
                    'course_id': 388899953570,
                    'course_contract': 'https://docs.google.com/document/d/1eR5rxgTZ0PXy_fYIFK2SS_Ro770IXxT9sM90vZr_OcU/edit',
                    'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09',
                                   'https://us02web.zoom.us/j/7890036306?pwd=WlpkV1JKUXZlQ3orYTd2dFBhZkdzdz09'],
                    'assignments_dictionary': {
                        'Create task practice 1': 'Create task practice',
                        'Create task practice 2': 'Create task practice',
                        'Create task practice 3': 'Create task practice',
                        'Create task practice 4': 'Create task practice',
                        'Create task practice 5': 'Create task practice',
                        'Create task practice 6': 'Create task practice',
                        'Create task 1': 'Create task',
                        'Create task 2': 'Create task',
                        'Create task 3': 'Create task',
                        'Create task 4': 'Create task',
                        'Create task 5': 'Create task',
                        'Create task 6': 'Create task',
                        'Create task 7': 'Create task',
                        'Create task 8': 'Create task',
                        'Create task 9': 'Create task',
                        'Create task 10': 'Create task',
                        'Create task 11': 'Create task',
                        'Create task 12': 'Create task',
                    },
                    'fy': False
                    }

classes = [it3_2022_fy_p3, it2_2022_fy_p3, ics_2022_s1_p1, apcsp_2022_s1_p4, apcsp_2022_s1_p1, it1_2022_fy_p1,
           web_2022_s1_p2, ]



# classes = [ apcsp_2022_s1_p4, ]
