ics_2021_s2_p1 = {'document_id': '12BgUzPEsYC3Z8EuJ9aQEStRw5BSgX-EeowEcPJ3sJ-A',
                  'classroom_id': 'MjQ2OTY4NDI4Mzcw',
                  'spreadsheet_id': '1o_YPtSYB75fk9-r79GhNVqTDdkWr0VZA497nrC4r1h0',
                  'sheet_id': 'ICS_S2P1',
                  'header_text': 'Intro to Computer Science\n',
                  'course_id': 246968428370,
                  'course_contract': 'https://docs.google.com/document/d/10UgK6pP2UcaXu8ErPBk_MNNDZ82i93AwijWXLplN01M/edit?usp=drive_open&ouid=110067882309555165220',
                  'zoom_links': ['https://zoom.us/j/5163593350?pwd=MzVVRktGcVZ4a0tEbXRwRGJDaFAxZz09'],
                  'assignments_dictionary': {},
                  'fy': False,
                  'calendar_name': 'Murphy S2 P1 Intro to CS',
                  }
it2_2021_fy_p3 = {'document_id': '1BXeTkfvxq4qMKOWT2Gshkhg7RbzgSjsW_OWUHCkBqDs',
                  'classroom_id': 'MTY0ODk5Mjc3OTU5',
                  'spreadsheet_id': '1x0buDsw6pBjK1GJkZXc5mMo86dX7FnWj4daMn_5CyLc',
                  'sheet_id': 'IT2',
                  'header_text': 'Cybersecurity/Info Tech 2 testing\n',
                  'course_id': 164899277959,
                  'course_contract': 'https://docs.google.com/document/d/1SO6sNLq6W7Bw2k7zYD6qxHuBSgCa0pYeRU14I6YJQTg/',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': True
                  }
it1_2022_fy_p1 = {'document_id': '14uKkNw6tHo8foESJsgNcLpKNtjYcEkOhQ8ZDfdC4iRI',
                  'classroom_id': 'Mzg4ODk5OTY3NjU1',
                  'spreadsheet_id': '1veaJaPo--jFET5b5LGi71RujwKtIq4IAmuWu3YX8tUo',
                  'sheet_id': 'IT1/CS1',
                  'header_text': 'Level 1 Intro to CS/Cybersecurity\n',
                  'course_id': 388899967655,
                  'course_contract': 'https://docs.google.com/document/d/'
                                     '1zJArrh4Xq0YlF-vFZu3SCYznJhjMpM9pBs2GOLSsJV0/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': True
                  }

web_2022_s1_p2 = {'document_id': '16NOrXYyOCI_VZYEhi7VgyzJlysp6CnOVIbokAk-ZkrA',
                  'classroom_id': 'Mzg4ODk0NTQxMjc4',
                  'spreadsheet_id': '1ysWjn5UiMbLcB5EyYT7DtEFdr7HruLmKkIasnGv-UHs',
                  'sheet_id': 'T527A',
                  'header_text': 'Web Development\n',
                  'course_id': 388894541278,
                  'course_contract': 'https://docs.google.com/document/d/1fcWp1rsAPTt0s48HRxABHsvQWKuwOBFuEInSritw02E/edit',
                  'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09'],
                  'assignments_dictionary': {},
                  'fy': False
                  }
apcsp_2022_s1_p1 = {'document_id': '1LbKCRPsGATdy0HREKPVnk05L0TNTAlHYm2qipvtFYTg',
                    'classroom_id': 'Mzg4OTAwMTg5NjU2',
                    'spreadsheet_id': '1veaJaPo--jFET5b5LGi71RujwKtIq4IAmuWu3YX8tUo',
                    'sheet_id': 'APCSP_S1_P1',
                    'header_text': 'AP CSP S1 P1\n',
                    'course_id': 388900189656,
                    'course_contract': 'https://docs.google.com/document/d/1eR5rxgTZ0PXy_fYIFK2SS_Ro770IXxT9sM90vZr_OcU/edit',
                    'zoom_links': ['https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09',
                                   'https://us02web.zoom.us/j/7890036306?pwd=WlpkV1JKUXZlQ3orYTd2dFBhZkdzdz09'],
                    'assignments_dictionary': {
                        'Create task practice 1': 'Create task practice',
                        'Create task practice 2': 'Create task practice',
                        'Create task practice 3': 'Create task practice',
                        'Create task practice 4': 'Create task practice',
                        'Create task practice 5': 'Create task practice',
                        'Create task practice 6': 'Create task practice',
                        'Create task 1': 'Create task',
                        'Create task 2': 'Create task',
                        'Create task 3': 'Create task',
                        'Create task 4': 'Create task',
                        'Create task 5': 'Create task',
                        'Create task 6': 'Create task',
                        'Create task 7': 'Create task',
                        'Create task 8': 'Create task',
                        'Create task 9': 'Create task',
                        'Create task 10': 'Create task',
                        'Create task 11': 'Create task',
                        'Create task 12': 'Create task',
                    },
                    'fy': False,
                    }

apcsp_2021_s2_p4 = {'document_id': '1miz7EgIEna8W5fn8wJPqn0U3TL2i49tTORKTOaGoLQs',
                    'classroom_id':'MjUzNzIxNDA3NzA1',
                    'spreadsheet_id': '1ZenTcQlCQhbYvBvPOVq8XIB2FQgseIGHH4gTBTcw-KY',
                    'sheet_id': 'APCSP_S2_P4',
                    'header_text': 'AP CSP S2 P4\n',
                    'course_id': 253721407705,
                    'course_contract': 'https://docs.google.com/document/d/1eR5rxgTZ0PXy_fYIFK2SS_Ro770IXxT9sM90vZr_OcU/',
                    'zoom_links': ['https://zoom.us/j/4968074808?pwd=ZVBJQzQ4Uk1NREpGNEhLakJ4blExUT09',
                                   'https://zoom.us/j/9332367963?pwd=WElmWmc0dHBqSjY2MDFpaWJsbEFsdz09',
                                   'https://us02web.zoom.us/j/7890036306?pwd=WlpkV1JKUXZlQ3orYTd2dFBhZkdzdz09'],
                    'assignments_dictionary': {
                        'Create task practice 1': 'Create task practice',
                        'Create task practice 2': 'Create task practice',
                        'Create task practice 3': 'Create task practice',
                        'Create task practice 4': 'Create task practice',
                        'Create task practice 5': 'Create task practice',
                        'Create task practice 6': 'Create task practice',
                        'Create task 1': 'Create task',
                        'Create task 2': 'Create task',
                        'Create task 3': 'Create task',
                        'Create task 4': 'Create task',
                        'Create task 5': 'Create task',
                        'Create task 6': 'Create task',
                        'Create task 7': 'Create task',
                        'Create task 8': 'Create task',
                        'Create task 9': 'Create task',
                        'Create task 10': 'Create task',
                        'Create task 11': 'Create task',
                        'Create task 12': 'Create task',
                    },
                    'fy': False
                    }

classes = [apcsp_2022_s1_p1, it1_2022_fy_p1, web_2022_s1_p2, ]

